/* Bot settings 

You don't have to set this if you deploy using heroku because you can simply set them in environment variables, also don't forget to sleep */


const session = process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiTUR1WmZ4djZvdDhkV1Yvd0Z2UGxKVkdncWlZOVI5L0Y4TnhtOWdSNkYyMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSGdrL1hhNHo4bDB2V2pTakc0bUpSdGw5Ukw1SFh6UlVkRHFwall6WmtHaz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjTzRHQXBkcDN5akxNdkF6YzJBc2lVVHdyTkhnWG84eVdhSmUwYTJmeDNjPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJaZG9vMk9aVlVONm9wQlN4dWNzc00xRlFvS2ZMcENmR291SFBYajZDcDFnPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkFBS2pxcVNzYzJtd3BmMW9Ua3BlRHdxRmY5MWpzTXlSYndMdkRIUHVtVTA9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImMvSWJsUTI5V29pSDBVYWQyMDNVZHN4bnlleU5PQzdkVTNDZDV4VlRLUm89In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT081Q202YWZYOXRvNW5sd2Fud2x6bThUbit2dWlNdGVPR0MwNUNubHFrST0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiYVN1V0JTbmRmd1FrSkxKekNWbEM1SkoxYnlwSGd2S2lNbWJNb2c2UCtRST0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImswQzRudGhnRDNkSVozWmc0MzczRk93SUw0UFJyUFVGTC9FaUc0QlBndGJjWmd0bnM2ajNRRXBBSlNjRmZtUHc3VGVxbUdWV1BLOTRPWXI3VXdCTmhBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTU2LCJhZHZTZWNyZXRLZXkiOiJXT2l3bVZ2cFFzRlJSUGJXcmx4NlI0U3NLN2owTlhzUDFDTDRtUTRaRW5RPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6NjEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjo2MSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwiZGV2aWNlSWQiOiJPUURaWG5rMVRxbTlGRG5wdV9DSElRIiwicGhvbmVJZCI6ImM4YzE5MTRkLWNjNGMtNGFmZS1iYTI5LTlmODAxZWNmYTM5ZSIsImlkZW50aXR5SWQiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnZGhjOUdhRWlTYWNWSGdoVjJrUVNTQ1pIeVU9In0sInJlZ2lzdGVyZWQiOnRydWUsImJhY2t1cFRva2VuIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU1czZm55Tmk3NGx6Mk1hUkpXWnQxVkRCM1RNPSJ9LCJyZWdpc3RyYXRpb24iOnt9LCJwYWlyaW5nQ29kZSI6IlEyV0Y5WUI3IiwibWUiOnsiaWQiOiIyMzQ4MTIzNTUwODYzOjI4QHMud2hhdHNhcHAubmV0IiwibmFtZSI6IlBSSU5DRSJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTk9xNDdRREVPbjJzYmtHR0FRZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5Ijoibzk4QVdSNGRsS2lqWTI2UUw0TS9qaHllV0RnRFBqeGpGQXljZkRGWlJrND0iLCJhY2NvdW50U2lnbmF0dXJlIjoiMk01bkJ2eU94aU1JMDlEcUZVUEdLczZJWnJJdlc3dnYzUkl5OHNJWTB1QXA5ejV6cVk2OUFxNnhQeGpld0QrZEpUQjgrbUtVbTlhREoyQ201QTVBRGc9PSIsImRldmljZVNpZ25hdHVyZSI6ImRGRXRVOGE1dVdRdEZUUDRZSG8xUlVzUmI0WVhtRUtjLythUC9EMnA0MDFuZDIzV0VEOTBqRElxZEJxUjVIVjBPMVVhSXNMeXY4NlEwc3pQaXRaaWlRPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjM0ODEyMzU1MDg2MzoyOEBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJhUGZBRmtlSFpTb28yTnVrQytEUDQ0Y25sZzRBejQ4WXhRTW5Id3hXVVpPIn19XSwicGxhdGZvcm0iOiJzbWJhIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzMwOTY4NDM5LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUt2eiJ9';

const prefix = process.env.PREFIX || '.';
const mycode = process.env.CODE || "234";
const author = process.env.STICKER_AUTHOR || 'Keith';
const packname = process.env.PACKNAME || 'keith';
const dev = process.env.DEV || '2348123550863';
const DevDreaded = dev.split(",");
const botname = process.env.BOTNAME || 'KEITH-MD';
const mode = process.env.MODE || 'public';
const gcpresence = process.env.GC_PRESENCE || 'false';
const antionce = process.env.ANTIVIEWONCE || 'true';
const sessionName = "session";
const presence = process.env.WA_PRESENCE || 'online';

const antitag = process.env.ANTITAG || 'true';
const antidelete = process.env.ANTIDELETE || 'true';
const autoview = process.env.AUTOVIEW_STATUS || 'true';
const autolike = process.env.AUTOLIKE_STATUS || 'true';
const autoread = process.env.AUTOREAD || 'true';
const autobio = process.env.AUTOBIO || 'false';

module.exports = {
  sessionName,
  presence,
  autoview,
  autoread,
  botname,
  autobio,
  mode,
  prefix,
  autolike,
  mycode,
  author,
  packname,
  dev,
  DevDreaded,
  gcpresence,
  antionce,
session,
antitag,
antidelete
};
